---
title: "mywork"
author: "Nicole Riordan"
date: "5/16/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
pluralize_gift <- function(gift){
gift <- gift %>%
paste0("s")
new <- gift
str_replace(gift ,"ys$", "ies")
str_replace(gift ,"ooses", "eese")
return(new)
}
pluralize_gift (xmas$Gift.Item)
```


```{r}
make_phrase <- function(num_word, item, verb, adjective, location){
  verb <- str_replace_na(verb, "")
  location <- str_replace_na(location, "")
  adjective <- str_replace_na(adjective, "")
 phrase <- str_c (num_word, adjective, item, verb, location, sep = " ")
return (phrase)
}

make_phrase( num_word = "ten", item = "lords", verb = "a-leaping", adjective = "", location = "")
make_phrase(xmas$Day, xmas$Gift.Item, xmas$Verb, xmas$Adjective, xmas$Location)

xmas <- xmas %>%
  mutate(
    Full.Phrase = make_phrase(Day, Gift.Item, Verb, Adjective, Location)
  )
```

```{r}
sing_day <- function(dataset, line, phrase_col){

  phrases <- dataset %>% pull({{phrase_col}})




}
```

